#---------------------------------------------------------
# GitHub Action - Basic
# 
# Copyleft (c) by https://github.com/LastHope0
#---------------------------------------------------------

name: GitAction

env:
  APPLICATION_NAME  : "HELLO"
  ACTOR             : "${{github.GITHUB_ACTOR}}"
  ACTOR_ID          : "${{github.GITHUB_ACTOR_ID}}"
  RUNNER_TEMP       : "${{github.RUNNER_TEMP}}"

on: 
  push:
    branches: 
      - main
      
jobs:

  testing:
    runs-on: ubuntu-latest
  
    steps:
      - name: Print system info
        run: 
          echo "Hello!\n"
          echo "Application name:${{env.APPLICATION_NAME}}\n"
          echo "Actor:${{env.ACTOR}}\n"
          echo "Actor id:${{env.ACTOR_ID}}\n"
          echo "Runner temp:${{env.RUNNER_TEMP}}\n"
      
      
  building:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: Print directiry
        run:
          ls -al
          
      - name: Test GO version
        run: 
          go --verion
